/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flavt.slg.app.phase.shift.setup.tool.main;

/**
 *
 * @author yaroslav
 */
public class SLG_PSST_MainFrame extends javax.swing.JFrame {
    private final SLG_PSST_App theApp;
    /**
     * Creates new form MainFrame
     */
    public SLG_PSST_MainFrame( SLG_PSST_App app) {
        theApp = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 500));
        setMinimumSize(new java.awt.Dimension(850, 500));
        setPreferredSize(new java.awt.Dimension(850, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><b><u>Фазовый сдвиг</b></u></html>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 10, 270, 30);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(360, 40, 60, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><b><u>Температура</b></u></html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 270, 30);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(360, 70, 60, 30);

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("-50");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(80, 70, 60, 30);

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(360, 100, 60, 30);

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("-40");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(80, 100, 60, 30);

        jTextField7.setEditable(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(360, 130, 60, 30);

        jTextField8.setEditable(false);
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("-30");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(80, 130, 60, 30);

        jTextField9.setEditable(false);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(360, 160, 60, 30);

        jTextField10.setEditable(false);
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("-20");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(80, 160, 60, 30);

        jTextField11.setEditable(false);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(360, 190, 60, 30);

        jTextField12.setEditable(false);
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("-10");
        getContentPane().add(jTextField12);
        jTextField12.setBounds(80, 190, 60, 30);

        jTextField13.setEditable(false);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(360, 220, 60, 30);

        jTextField14.setEditable(false);
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("0");
        getContentPane().add(jTextField14);
        jTextField14.setBounds(80, 220, 60, 30);

        jTextField15.setEditable(false);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(360, 250, 60, 30);

        jTextField16.setEditable(false);
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("10");
        getContentPane().add(jTextField16);
        jTextField16.setBounds(80, 250, 60, 30);

        jTextField17.setEditable(false);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(360, 280, 60, 30);

        jTextField18.setEditable(false);
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("20");
        getContentPane().add(jTextField18);
        jTextField18.setBounds(80, 280, 60, 30);

        jTextField19.setEditable(false);
        getContentPane().add(jTextField19);
        jTextField19.setBounds(360, 310, 60, 30);

        jTextField20.setEditable(false);
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("30");
        getContentPane().add(jTextField20);
        jTextField20.setBounds(80, 310, 60, 30);

        jTextField21.setEditable(false);
        getContentPane().add(jTextField21);
        jTextField21.setBounds(360, 340, 60, 30);

        jTextField22.setEditable(false);
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("50");
        getContentPane().add(jTextField22);
        jTextField22.setBounds(80, 370, 60, 30);

        jTextField23.setEditable(false);
        getContentPane().add(jTextField23);
        jTextField23.setBounds(360, 400, 60, 30);

        jTextField24.setEditable(false);
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText("40");
        getContentPane().add(jTextField24);
        jTextField24.setBounds(80, 340, 60, 30);

        jTextField25.setEditable(false);
        getContentPane().add(jTextField25);
        jTextField25.setBounds(360, 370, 60, 30);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton1.setText("set");
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 70, 60, 30);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton2.setText("req");
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 70, 60, 30);

        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField26);
        jTextField26.setBounds(150, 70, 60, 30);

        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField27);
        jTextField27.setBounds(150, 100, 60, 30);

        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField28);
        jTextField28.setBounds(150, 130, 60, 30);

        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField29);
        jTextField29.setBounds(150, 160, 60, 30);

        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField30);
        jTextField30.setBounds(150, 190, 60, 30);

        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField31);
        jTextField31.setBounds(150, 220, 60, 30);

        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField32);
        jTextField32.setBounds(150, 250, 60, 30);

        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField33);
        jTextField33.setBounds(150, 280, 60, 30);

        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField34);
        jTextField34.setBounds(150, 310, 60, 30);

        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField35);
        jTextField35.setBounds(150, 370, 60, 30);

        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField36);
        jTextField36.setBounds(150, 340, 60, 30);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton3.setText("set");
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 100, 60, 30);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton4.setText("req");
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 100, 60, 30);

        jButton5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton5.setText("set");
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 160, 60, 30);

        jButton6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton6.setText("req");
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 160, 60, 30);

        jButton7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton7.setText("set");
        getContentPane().add(jButton7);
        jButton7.setBounds(220, 130, 60, 30);

        jButton8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton8.setText("req");
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 130, 60, 30);

        jButton9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton9.setText("req");
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 250, 60, 30);

        jButton10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton10.setText("set");
        getContentPane().add(jButton10);
        jButton10.setBounds(220, 280, 60, 30);

        jButton11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton11.setText("req");
        getContentPane().add(jButton11);
        jButton11.setBounds(10, 280, 60, 30);

        jButton12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton12.setText("set");
        getContentPane().add(jButton12);
        jButton12.setBounds(220, 250, 60, 30);

        jButton13.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton13.setText("req");
        getContentPane().add(jButton13);
        jButton13.setBounds(10, 220, 60, 30);

        jButton14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton14.setText("req");
        getContentPane().add(jButton14);
        jButton14.setBounds(10, 190, 60, 30);

        jButton15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton15.setText("set");
        getContentPane().add(jButton15);
        jButton15.setBounds(220, 190, 60, 30);

        jButton16.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton16.setText("set");
        getContentPane().add(jButton16);
        jButton16.setBounds(220, 220, 60, 30);

        jButton17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton17.setText("req");
        getContentPane().add(jButton17);
        jButton17.setBounds(10, 370, 60, 30);

        jButton20.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton20.setText("set");
        getContentPane().add(jButton20);
        jButton20.setBounds(220, 370, 60, 30);

        jButton21.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton21.setText("req");
        getContentPane().add(jButton21);
        jButton21.setBounds(10, 340, 60, 30);

        jButton22.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton22.setText("req");
        getContentPane().add(jButton22);
        jButton22.setBounds(10, 310, 60, 30);

        jButton23.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton23.setText("set");
        getContentPane().add(jButton23);
        jButton23.setBounds(220, 310, 60, 30);

        jButton24.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton24.setText("set");
        getContentPane().add(jButton24);
        jButton24.setBounds(220, 340, 60, 30);
        getContentPane().add(jTextField37);
        jTextField37.setBounds(430, 70, 60, 30);
        getContentPane().add(jTextField38);
        jTextField38.setBounds(430, 100, 60, 30);
        getContentPane().add(jTextField39);
        jTextField39.setBounds(430, 130, 60, 30);
        getContentPane().add(jTextField40);
        jTextField40.setBounds(430, 160, 60, 30);
        getContentPane().add(jTextField41);
        jTextField41.setBounds(430, 190, 60, 30);
        getContentPane().add(jTextField42);
        jTextField42.setBounds(430, 220, 60, 30);
        getContentPane().add(jTextField43);
        jTextField43.setBounds(430, 250, 60, 30);
        getContentPane().add(jTextField44);
        jTextField44.setBounds(430, 280, 60, 30);
        getContentPane().add(jTextField45);
        jTextField45.setBounds(430, 310, 60, 30);
        getContentPane().add(jTextField46);
        jTextField46.setBounds(430, 340, 60, 30);
        getContentPane().add(jTextField47);
        jTextField47.setBounds(430, 400, 60, 30);
        getContentPane().add(jTextField48);
        jTextField48.setBounds(430, 370, 60, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(430, 40, 60, 30);

        jButton18.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton18.setText("set");
        getContentPane().add(jButton18);
        jButton18.setBounds(500, 40, 60, 30);

        jButton19.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton19.setText("set");
        getContentPane().add(jButton19);
        jButton19.setBounds(500, 70, 60, 30);

        jButton25.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton25.setText("set");
        getContentPane().add(jButton25);
        jButton25.setBounds(500, 130, 60, 30);

        jButton26.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton26.setText("set");
        getContentPane().add(jButton26);
        jButton26.setBounds(500, 100, 60, 30);

        jButton27.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton27.setText("set");
        getContentPane().add(jButton27);
        jButton27.setBounds(500, 250, 60, 30);

        jButton28.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton28.setText("set");
        getContentPane().add(jButton28);
        jButton28.setBounds(500, 220, 60, 30);

        jButton29.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton29.setText("set");
        getContentPane().add(jButton29);
        jButton29.setBounds(500, 160, 60, 30);

        jButton30.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton30.setText("set");
        getContentPane().add(jButton30);
        jButton30.setBounds(500, 190, 60, 30);

        jButton31.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton31.setText("set");
        getContentPane().add(jButton31);
        jButton31.setBounds(500, 340, 60, 30);

        jButton32.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton32.setText("set");
        getContentPane().add(jButton32);
        jButton32.setBounds(500, 280, 60, 30);

        jButton33.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton33.setText("set");
        getContentPane().add(jButton33);
        jButton33.setBounds(500, 310, 60, 30);

        jButton34.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton34.setText("req");
        getContentPane().add(jButton34);
        jButton34.setBounds(290, 40, 60, 30);

        jButton35.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton35.setText("req");
        getContentPane().add(jButton35);
        jButton35.setBounds(290, 70, 60, 30);

        jButton36.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton36.setText("req");
        getContentPane().add(jButton36);
        jButton36.setBounds(290, 130, 60, 30);

        jButton37.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton37.setText("req");
        getContentPane().add(jButton37);
        jButton37.setBounds(290, 100, 60, 30);

        jButton38.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton38.setText("req");
        getContentPane().add(jButton38);
        jButton38.setBounds(290, 220, 60, 30);

        jButton39.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton39.setText("req");
        getContentPane().add(jButton39);
        jButton39.setBounds(290, 250, 60, 30);

        jButton40.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton40.setText("req");
        getContentPane().add(jButton40);
        jButton40.setBounds(290, 190, 60, 30);

        jButton41.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton41.setText("req");
        getContentPane().add(jButton41);
        jButton41.setBounds(290, 160, 60, 30);

        jButton42.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton42.setText("req");
        getContentPane().add(jButton42);
        jButton42.setBounds(290, 340, 60, 30);

        jButton43.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton43.setText("req");
        getContentPane().add(jButton43);
        jButton43.setBounds(290, 310, 60, 30);

        jButton44.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton44.setText("req");
        getContentPane().add(jButton44);
        jButton44.setBounds(290, 280, 60, 30);

        jButton45.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton45.setText("req");
        getContentPane().add(jButton45);
        jButton45.setBounds(290, 400, 60, 30);

        jButton46.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton46.setText("req");
        getContentPane().add(jButton46);
        jButton46.setBounds(290, 370, 60, 30);

        jButton47.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton47.setText("set");
        getContentPane().add(jButton47);
        jButton47.setBounds(500, 400, 60, 30);

        jButton48.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton48.setText("set");
        getContentPane().add(jButton48);
        jButton48.setBounds(500, 370, 60, 30);

        jButton49.setText("Выход");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton49);
        jButton49.setBounds(580, 270, 260, 40);

        jButton50.setText("Соединиться с прибором");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton50);
        jButton50.setBounds(580, 70, 260, 40);

        jButton51.setText("Обновить (запросить) таблицы");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton51);
        jButton51.setBounds(580, 220, 260, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton49ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
